
volumes:
    logs:
        driver: local

services:
    

    corsihead:
        build: ./docker
        container_name: CORSI_HEAD
        working_dir: /var/www/public_html
        command: sh -c "cd /var/www && [ ! -d vendor ] && composer install --no-interaction --dev;  php -S 0.0.0.0:8080 -t ./public_html "
        stdin_open: true 
        tty: true
        environment:
            docker: "true"
        ports:
            - 6060:8080
        volumes:
            - .:/var/www
            - logs:/var/www/logs
        networks:
            - app-network
        healthcheck:
            disable: true                   
                         

networks:
    app-network:
        driver: bridge